import { useEffect, useState } from "react";
import { Bell, Download, KeyRound, Loader2, ShieldAlert, ShieldCheck, Smartphone, Target, Trash2, UserRound, X } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Input } from "@/components/ui/input";

type AccountUser = { name: string; username: string | null; email: string | null; cpf?: string | null; role: "user" | "admin" };
const fmt=(value?:string|null)=>value?new Date(value).toLocaleString("pt-BR"):"—";

export function AccountPanel({ user, onClose }: { user: AccountUser; onClose: () => void }) {
  const [profile,setProfile]=useState({name:user.name,username:user.username??"",email:user.email??"",cpf:user.cpf??""});
  const [password,setPassword]=useState({currentPassword:"",newPassword:"",confirmation:""});
  const [prefs,setPrefs]=useState({emailSecurityAlerts:true,emailCourseUpdates:true,weeklyGoalQuestions:50,weeklyGoalDays:5,examDate:"",reducedMotion:false,compactMode:false});
  const [deleteConfirmation,setDeleteConfirmation]=useState("");
  const [message,setMessage]=useState<string|null>(null);
  const utils=trpc.useUtils();
  const preferences=trpc.auth.preferences.useQuery();
  const sessions=trpc.auth.sessions.useQuery();
  const securityEvents=trpc.auth.securityEvents.useQuery();
  const weeklyGoal=trpc.study.weeklyGoal.useQuery();
  const mfa=trpc.auth.mfa.useQuery();
  const [mfaSetup,setMfaSetup]=useState<{secret:string;otpauthUri:string}|null>(null);
  const [mfaCode,setMfaCode]=useState("");
  const [mfaPassword,setMfaPassword]=useState("");
  const [backupCodes,setBackupCodes]=useState<string[]>([]);
  useEffect(()=>{if(preferences.data)setPrefs({...preferences.data,examDate:preferences.data.examDate??""});},[preferences.data]);

  const fail=(error:unknown)=>setMessage((error as {message?:string})?.message??"Não foi possível concluir a atualização.");
  const updateProfile=trpc.auth.updateProfile.useMutation({onSuccess:async()=>{await utils.auth.me.invalidate();setMessage("Dados atualizados.");},onError:fail});
  const changePassword=trpc.auth.changePassword.useMutation({onSuccess:()=>{setPassword({currentPassword:"",newPassword:"",confirmation:""});setMessage("Senha alterada e outras sessões encerradas.");void sessions.refetch();},onError:fail});
  const savePrefs=trpc.auth.updatePreferences.useMutation({onSuccess:()=>{setMessage("Preferências salvas.");void preferences.refetch();void weeklyGoal.refetch();},onError:fail});
  const revoke=trpc.auth.revokeSession.useMutation({onSuccess:(data:any)=>{setMessage(data.current?"Sessão atual encerrada.":"Dispositivo desconectado.");if(data.current)window.location.assign("/");else void sessions.refetch();},onError:fail});
  const exportData=trpc.auth.exportData.useMutation({onSuccess:(data:any)=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="meus-dados-nucleo.json";a.click();URL.revokeObjectURL(url);setMessage("Cópia dos seus dados gerada.");},onError:fail});
  const deleteAccount=trpc.auth.deleteAccount.useMutation({onSuccess:()=>window.location.assign("/"),onError:fail});
  const startMfa=trpc.auth.mfaSetup.useMutation({onSuccess:(data:any)=>{setMfaSetup(data);setBackupCodes([]);setMessage("Configuração iniciada. Adicione a chave no seu aplicativo autenticador.");},onError:fail});
  const confirmMfa=trpc.auth.mfaConfirm.useMutation({onSuccess:(data:any)=>{setBackupCodes(data.backupCodes??[]);setMfaSetup(null);setMfaCode("");setMessage("Autenticação em dois fatores ativada.");void mfa.refetch();},onError:fail});
  const disableMfa=trpc.auth.mfaDisable.useMutation({onSuccess:()=>{setMfaPassword("");setMfaCode("");setBackupCodes([]);setMessage("Autenticação em dois fatores desativada.");void mfa.refetch();},onError:fail});
  const regenerateMfa=trpc.auth.mfaBackupCodes.useMutation({onSuccess:(data:any)=>{setBackupCodes(data.backupCodes??[]);setMfaCode("");setMessage("Novos códigos de recuperação gerados. Os anteriores foram invalidados.");},onError:fail});
  const pending=updateProfile.isPending||changePassword.isPending||savePrefs.isPending;

  return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#152d38]/55 p-2 backdrop-blur-sm sm:p-3"><section role="dialog" aria-modal="true" aria-labelledby="perfil-titulo" className="max-h-[96dvh] w-full max-w-3xl overflow-y-auto rounded-[1.2rem] border border-[#d7cfc1] bg-[#fffdf8] shadow-2xl sm:max-h-[92vh] sm:rounded-[1.35rem]"><header className="sticky top-0 z-10 flex items-start justify-between border-b border-[#e5ddd0] bg-[#fffdf8]/95 p-4 backdrop-blur sm:p-5"><div><p className="eyebrow">CONTA PRIVADA</p><h2 id="perfil-titulo" className="font-display mt-1 text-xl font-bold text-[#173d4a]">Conta, segurança e preferências</h2></div><button onClick={onClose} aria-label="Fechar perfil" className="grid h-10 w-10 place-items-center rounded-xl border border-[#ded6c9]"><X className="h-4 w-4"/></button></header><div className="space-y-6 p-4 sm:p-7">
    <section className="rounded-2xl border border-[#c5dad5] bg-[#f3faf8] p-4"><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#0e5a70]"/><p className="text-sm leading-6 text-[#315a5d]">Dados sensíveis, sessões e histórico de segurança são controlados pelo servidor. Você pode desconectar dispositivos e exportar seus dados a qualquer momento.</p></div></section>

    <section><div className="mb-4 flex items-center gap-2"><UserRound className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Dados básicos</h3></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Nome completo<Input value={profile.name} onChange={e=>setProfile(v=>({...v,name:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Usuário<Input value={profile.username} onChange={e=>setProfile(v=>({...v,username:e.target.value.toLowerCase()}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">E-mail<Input type="email" value={profile.email} onChange={e=>setProfile(v=>({...v,email:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold sm:col-span-2">CPF<Input inputMode="numeric" value={profile.cpf} onChange={e=>setProfile(v=>({...v,cpf:e.target.value}))} className="mt-1.5 h-11 bg-white" placeholder="Somente para identificação da conta"/></label></div><button disabled={pending} onClick={()=>updateProfile.mutate(profile)} className="action-button mt-4 disabled:opacity-60">Salvar dados</button></section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><Target className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Meta e experiência</h3></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold">Questões/semana<Input type="number" min={1} max={5000} value={prefs.weeklyGoalQuestions} onChange={e=>setPrefs(v=>({...v,weeklyGoalQuestions:Number(e.target.value)}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Dias/semana<Input type="number" min={1} max={7} value={prefs.weeklyGoalDays} onChange={e=>setPrefs(v=>({...v,weeklyGoalDays:Number(e.target.value)}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Data da prova<Input type="date" value={prefs.examDate} onChange={e=>setPrefs(v=>({...v,examDate:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label></div>{weeklyGoal.data&&<div className="mt-3 grid gap-2 sm:grid-cols-2"><div className="rounded-xl border bg-white p-3 text-xs"><strong>{weeklyGoal.data.questions.current}/{weeklyGoal.data.questions.target}</strong> questões nesta semana</div><div className="rounded-xl border bg-white p-3 text-xs"><strong>{weeklyGoal.data.days.current}/{weeklyGoal.data.days.target}</strong> dias estudados</div></div>}<div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border bg-white p-3 text-xs font-semibold"><input type="checkbox" checked={prefs.reducedMotion} onChange={e=>setPrefs(v=>({...v,reducedMotion:e.target.checked}))}/>Reduzir animações</label><label className="flex items-center gap-2 rounded-xl border bg-white p-3 text-xs font-semibold"><input type="checkbox" checked={prefs.compactMode} onChange={e=>setPrefs(v=>({...v,compactMode:e.target.checked}))}/>Interface compacta</label></div><div className="mt-3 grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border bg-white p-3 text-xs font-semibold"><Bell className="h-4 w-4"/><input type="checkbox" checked={prefs.emailSecurityAlerts} onChange={e=>setPrefs(v=>({...v,emailSecurityAlerts:e.target.checked}))}/>Alertas de segurança por e-mail</label><label className="flex items-center gap-2 rounded-xl border bg-white p-3 text-xs font-semibold"><input type="checkbox" checked={prefs.emailCourseUpdates} onChange={e=>setPrefs(v=>({...v,emailCourseUpdates:e.target.checked}))}/>Novidades dos cursos por e-mail</label></div><button disabled={savePrefs.isPending} onClick={()=>savePrefs.mutate(prefs)} className="ghost-button mt-4">Salvar preferências</button></section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><Smartphone className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Dispositivos conectados</h3></div><div className="space-y-2">{sessions.data?.map((s:any)=><div key={s.id} className="flex flex-col gap-3 rounded-xl border bg-white p-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><p className="truncate text-xs font-bold text-[#25434e]">{s.current?"Este dispositivo":s.userAgent||"Dispositivo não identificado"}</p><p className="mt-1 text-[10px] text-[#718087]">Última atividade: {fmt(s.lastSeenAt)}{s.revokedAt?" · revogada":""}</p></div>{!s.revokedAt&&<button onClick={()=>revoke.mutate({id:s.id})} disabled={revoke.isPending} className="ghost-button px-3 py-2 text-xs">{s.current?"Encerrar sessão":"Desconectar"}</button>}</div>)}</div></section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><ShieldAlert className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Atividade de segurança</h3></div><div className="space-y-2">{securityEvents.data?.slice(0,8).map((e:any)=><div key={e.id} className="rounded-xl border bg-white p-3"><p className="text-xs font-bold">{String(e.type).replaceAll("_"," ")}</p><p className="mt-1 text-[10px] text-[#718087]">{fmt(e.createdAt)}{e.userAgent?" · "+e.userAgent:""}</p></div>)}</div></section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Autenticação em dois fatores</h3></div><p className="text-xs leading-5 text-[#60777a]">{mfa.data?.enabled?"Ativada. Além da senha, novos logins exigem um código temporário.":"Opcional e recomendada, principalmente para contas administrativas."}</p>{!mfa.data?.enabled&&!mfaSetup&&<button onClick={()=>startMfa.mutate({})} className="ghost-button mt-3">Configurar autenticador</button>}{mfaSetup&&<div className="mt-3 rounded-xl border bg-white p-4"><p className="text-xs font-bold">1. Adicione esta chave no Google Authenticator, Microsoft Authenticator, 1Password ou equivalente:</p><code className="mt-2 block break-all rounded-lg bg-[#f3efe6] p-3 text-xs">{mfaSetup.secret}</code><p className="mt-3 text-[11px] text-[#60777a]">Conta: {user.email??user.username}. Depois informe o código de 6 dígitos.</p><Input value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\D/g,"").slice(0,6))} inputMode="numeric" autoComplete="one-time-code" placeholder="000000" className="mt-3 h-11"/><button disabled={mfaCode.length!==6||confirmMfa.isPending} onClick={()=>confirmMfa.mutate({code:mfaCode})} className="action-button mt-3 disabled:opacity-50">Confirmar e ativar</button></div>}{mfa.data?.enabled&&<div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Código atual<Input value={mfaCode} onChange={e=>setMfaCode(e.target.value.replace(/\s/g,"").slice(0,32))} autoComplete="one-time-code" className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Senha atual (para desativar)<Input type="password" value={mfaPassword} onChange={e=>setMfaPassword(e.target.value)} autoComplete="current-password" className="mt-1.5 h-11 bg-white"/></label><div className="flex flex-wrap gap-2 sm:col-span-2"><button disabled={!mfaCode} onClick={()=>regenerateMfa.mutate({code:mfaCode})} className="ghost-button text-xs">Gerar novos códigos de recuperação</button><button disabled={!mfaCode||!mfaPassword} onClick={()=>disableMfa.mutate({code:mfaCode,password:mfaPassword})} className="rounded-lg border border-[#b76950] px-3 py-2 text-xs font-bold text-[#8d3d27] disabled:opacity-50">Desativar 2 fatores</button></div></div>}{backupCodes.length>0&&<div className="mt-4 rounded-xl border border-[#e0b27d] bg-[#fff5e5] p-4"><p className="text-xs font-bold text-[#76541c]">Guarde estes códigos em local seguro. Cada um funciona uma única vez e eles não serão exibidos novamente.</p><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{backupCodes.map(code=><code key={code} className="rounded bg-white p-2 text-center text-xs font-bold">{code}</code>)}</div></div>}</section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-4 flex items-center gap-2"><KeyRound className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Alterar senha</h3></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold sm:col-span-2">Senha atual<Input type="password" autoComplete="current-password" value={password.currentPassword} onChange={e=>setPassword(v=>({...v,currentPassword:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Nova senha<Input type="password" autoComplete="new-password" value={password.newPassword} onChange={e=>setPassword(v=>({...v,newPassword:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label><label className="text-xs font-bold">Confirmar<Input type="password" autoComplete="new-password" value={password.confirmation} onChange={e=>setPassword(v=>({...v,confirmation:e.target.value}))} className="mt-1.5 h-11 bg-white"/></label></div><button disabled={pending} onClick={()=>changePassword.mutate(password)} className="ghost-button mt-4">Atualizar senha</button></section>

    <section className="border-t border-[#e6ded1] pt-6"><div className="mb-3 flex items-center gap-2"><Download className="h-4 w-4 text-[#0e5a70]"/><h3 className="font-display text-lg font-bold">Privacidade e portabilidade</h3></div><button onClick={()=>exportData.mutate({})} disabled={exportData.isPending} className="ghost-button"><Download className="h-4 w-4"/>Exportar meus dados</button><div className="mt-5 rounded-xl border border-[#e0b7a8] bg-[#fff2ed] p-4"><div className="flex gap-2"><Trash2 className="mt-0.5 h-4 w-4 text-[#9b4228]"/><div className="flex-1"><p className="text-xs font-bold text-[#8d3d27]">Excluir conta definitivamente</p><p className="mt-1 text-[11px] leading-5 text-[#79584e]">Digite seu usuário ou nome para confirmar. Esta ação remove seus dados associados.</p><Input value={deleteConfirmation} onChange={e=>setDeleteConfirmation(e.target.value)} className="mt-3 h-10 bg-white" placeholder={user.username??user.name}/><button disabled={!deleteConfirmation||deleteAccount.isPending} onClick={()=>deleteAccount.mutate({confirmation:deleteConfirmation})} className="mt-3 rounded-lg border border-[#b76950] px-3 py-2 text-xs font-bold text-[#8d3d27] disabled:opacity-50">Excluir minha conta</button></div></div></div></section>
    {message&&<p role="status" className="border border-[#b9d6cb] bg-[#edf8f4] px-3 py-2 text-xs font-semibold text-[#17644e]">{message}</p>}
  </div></section></div>;
}
